---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-chart-litmuschaos-server
  name: prod-chart-litmuschaos-server
  namespace: prod-hub-litmuschaos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-chart-litmuschaos-server
  template:
    metadata:
      labels:
        app: prod-chart-litmuschaos-server
    spec:
      containers:
        - name: prod-chart-litmuschaos-server
          image: litmuschaos/charthub-litmuschaos-io-server:a1277f
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 100Mi
              cpu: 100m
          imagePullPolicy: Always
          env:
            - name: CHAOS_CHART_BRANCH
              value: "master"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/analytics
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: analytic-auth
