---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-chart-litmuschaos-client
  name: prod-chart-litmuschaos-client
  namespace: prod-hub-litmuschaos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-chart-litmuschaos-client
  template:
    metadata:
      labels:
        app: prod-chart-litmuschaos-client
    spec:
      containers:
      - name: prod-chart-litmuschaos-client
        image: litmuschaos/charthub-litmuschaos-io:3d6202
        resources:
          limits:
            memory: 250Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 100m
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
