---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusdoc
  namespace: litmus-docs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: litmusdoc
  template:
    metadata:
      labels:
        app: litmusdoc
    spec:
      containers:
      - name: litmusdoc
        image: litmuschaos/litmus-docs:master-30f77a1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
